[package]
name = "quick_chat_c"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
quick_chat_lib = { path = "../quick_chat_lib" }

# log4rs
log = "0.4"
log4rs = "1.3.0"
